In [ ]:
#Import required libraries
import pandas as pd
import numpy as np

In [ ]:
#Loading dataset
df = pd.read_csv("/content/drive/MyDrive/Churn_Model/churn_customer.csv")

In [ ]:
df.head()

Unnamed: 0  ...  PaymentMethod_Mailed check
0           0  ...                           0
1           1  ...                           1
2           2  ...                           1
3           3  ...                           0
4           4  ...                           0

[5 rows x 28 columns]

In [ ]:
#Shape of the data
df.shape

(7032, 28)

In [ ]:
df.columns

Index(['Unnamed: 0', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'PaperlessBilling', 'MonthlyCharges', 'TotalCharges',
       'Churn', 'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [ ]:
df.drop('Unnamed: 0', axis = 1, inplace = True)

In [ ]:
df.head()

gender  ...  PaymentMethod_Mailed check
0       0  ...                           0
1       1  ...                           1
2       1  ...                           1
3       1  ...                           0
4       0  ...                           0

[5 rows x 27 columns]

In [ ]:
#Now we split dataset into independent variable & dependent variable
X = df.drop("Churn", axis = 1)
y = df['Churn']

In [ ]:
X.head()

gender  ...  PaymentMethod_Mailed check
0       0  ...                           0
1       1  ...                           1
2       1  ...                           1
3       1  ...                           0
4       0  ...                           0

[5 rows x 26 columns]

In [ ]:
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [ ]:
#Now splitting dataset into training & testing data 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [ ]:
print(x_train.shape, x_test.shape)

(5625, 26) (1407, 26)


In [ ]:
print(y_train.shape, y_test.shape)

(5625,) (1407,)


#### Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf_tree = DecisionTreeClassifier(criterion= 'gini', max_depth= 6, random_state= 101, min_samples_leaf= 8)

In [ ]:
#Train the model
clf_tree.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=6, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=8, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=101, splitter='best')

In [ ]:
#Model prediction
prediction = clf_tree.predict(x_test)

In [ ]:
#Let's check accuracy of the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
accuracy = accuracy_score(y_test, prediction)
accuracy

0.7746979388770433

In [ ]:
cm = confusion_matrix(y_test, prediction)
cm

array([[871, 162],
       [155, 219]])

In [ ]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.85      0.84      0.85      1033
           1       0.57      0.59      0.58       374

    accuracy                           0.77      1407
   macro avg       0.71      0.71      0.71      1407
weighted avg       0.78      0.77      0.78      1407



In [ ]:
df['Churn'].value_counts(normalize = True)

0    0.734215
1    0.265785
Name: Churn, dtype: float64

#### Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, criterion= 'gini', max_depth= 8, min_samples_leaf= 8, random_state= 101)

In [ ]:
classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=8, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=8, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=101,
                       verbose=0, warm_start=False)

In [ ]:
y_prediction = classifier.predict(x_test)

In [ ]:
forest_acc = accuracy_score(y_test, y_prediction)
forest_acc

0.7974413646055437

In [ ]:
cm = confusion_matrix(y_test, y_prediction)
cm

array([[941,  92],
       [193, 181]])

In [ ]:
print(classification_report(y_test, y_prediction))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1033
           1       0.66      0.48      0.56       374

    accuracy                           0.80      1407
   macro avg       0.75      0.70      0.71      1407
weighted avg       0.79      0.80      0.79      1407



In [ ]:
#Hyperparameter Tunnning

from sklearn.model_selection import RandomizedSearchCV
#Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start =100, stop = 1200, num = 10)]

#Number of features to be consider at every split
max_features = ['auto', 'sqrt', 'log2']

#Max number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000, 10)]

#Minimum number of samples required to split nodes
min_samples_split = [2,5, 10 , 14]

#Minimum number of samples required at each leaf node
min_samples_leaf = [1,2,4,6,8]

criterion = ['gini','entropy']
#Now create random grid
random_grid = {'n_estimators' : n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'criterion': criterion}

print(random_grid)

{'n_estimators': [100, 222, 344, 466, 588, 711, 833, 955, 1077, 1200], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['gini', 'entropy']}


In [ ]:
forest = RandomForestClassifier()

rf_randomcv = RandomizedSearchCV(estimator= forest, param_distributions= random_grid, n_iter = 50, scoring= 'accuracy',  cv = 10, random_state= 100)

In [ ]:
#fit randomsized model
rf_randomcv.fit(x_train, y_train)

RandomizedSearchCV(cv=10, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
              

In [ ]:
rf_randomcv.best_params_

{'criterion': 'entropy',
 'max_depth': 890,
 'max_features': 'auto',
 'min_samples_leaf': 8,
 'min_samples_split': 14,
 'n_estimators': 344}

In [ ]:
rf_randomcv.best_score_

0.8049818903560615

In [ ]:
y_pred = rf_randomcv.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.7995735607675906

In [ ]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[945,  88],
       [194, 180]])

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1033
           1       0.67      0.48      0.56       374

    accuracy                           0.80      1407
   macro avg       0.75      0.70      0.72      1407
weighted avg       0.79      0.80      0.79      1407

